services:
  - type: web
    name: lokswasthya-all-in-one
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: OLLAMA_BASE_URL
        sync: false
      - key: OLLAMA_MODEL
        value: health-assistantv3
      - key: OLLAMA_INTENT_MODEL
        value: llama3.2
